### PR TITLE
workaround for JavaFX preview in IntelliJ 

### PR DESCRIPTION
**Pull request by ahus1**
not supporting Twitter's widget.js, closes https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/235

### CODE REVIEW

**Comment by rdmueller** [comment]
wow. very cool! Thanx for the effort!

**Comment by ahus1** [comment]
I'll need at least one more try... the Netlify build is running again. Will remove the WIP once it's ready.

**Comment by ahus1** [comment]
Alright, preview looks better now. Ready for review (and merge).

**Comment by rdmueller** [comment]
works fine. THANX!

**Pull request merged**
